Repository adammast/RSCBot, pull requests merged in 2022-04, with the labels that each got.

#158 Balance team fixes
  sixMans/game.py
Labels: bug

#170 Stat Manager
  statsManager/__init__.py
  statsManager/statsManager.py
  teamManager/teamManager.py
Labels: enhancement

#177 statsManger update 7
  statsManager/statsManager.py
  statsManager/statsReference.py
Labels: enhancement

#185 Expire contracts
  .gitignore
  VSCode.md
  bulkRoleManager/bulkRoleManager.py
Labels: enhancement, Refactor
